export const countyTowns: Record<string, string[]> = {
  "Baringo": ["Kabarnet","Eldama Ravine","Marigat","Mogotio","Chemolingot","Kabartonjo"],
  "Bomet": ["Bomet Town","Sotik","Chepalungu","Longisa","Kaptenen","Mogogosiek"],
  "Bungoma": ["Bungoma Town","Kimilili","Webuye","Sirisia","Chwele","Bumula","Malakisi","Bokoli","Naitiri","Tongaren"],
  "Busia": ["Busia Town","Malaba","Nambale","Bumala","Port Victoria","Funyula","Butula","Amagoro"],
  "Elgeyo-Marakwet": ["Iten","Kapsowar","Chepkorio","Kaptarakwa"],
  "Embu": ["Embu Town","Runyenjes","Manyatta","Kiritiri","Siakago","Ishiara"],
  "Garissa": ["Garissa Town","Dadaab","Ijara","Balambala","Fafi"],
  "Homa Bay": ["Homa Bay Town","Oyugis","Kendubay","Mbita","Ndhiwa","Sindo","Rodi Kopany"],
  "Isiolo": ["Isiolo Town","Merti","Garbatulla","Kinna"],
  "Kajiado": ["Kajiado Town","Ngong","Kitengela","Loitokitok","Kiserian","Ongata Rongai","Isinya","Namanga"],
  "Kakamega": ["Kakamega Town","Mumias Town","Mumias Market","Shianda Market","Ekero Market","Shibale Market","Butere Town","Butere Market","Malava Town","Malava Market","Matungu Market","Khwisero Market","Lurambi","Lugari","Likuyani","Navakholo","Shinyalu","Bukura","Lumakanda","Khayega Market"],
  "Kericho": ["Kericho Town","Litein","Kipkelion","Londiani","Sosiot","Kapsoit"],
  "Kiambu": ["Kiambu Town","Thika Town","Ruiru","Limuru","Kikuyu","Juja","Githunguri","Gatundu","Banana Market","Kijabe Market"],
  "Kilifi": ["Kilifi Town","Malindi","Watamu","Mariakani","Kaloleni","Mtwapa","Mazeras","Ganze","Magarini"],
  "Kirinyaga": ["Kerugoya","Kagio","Sagana","Kutus","Wanguru","Kianyaga","Baricho"],
  "Kisii": ["Kisii Town","Ogembo","Nyamache","Suneka","Marani","Keroka","Masimba","Gesusu"],
  "Kisumu": ["Kisumu Town","Maseno","Ahero","Kombewa","Muhoroni","Kibos","Nyamasaria","Kondele","Sondu"],
  "Kitui": ["Kitui Town","Mwingi Town","Mutomo","Kabati","Kauwi","Zombe","Migwani"],
  "Kwale": ["Kwale Town","Ukunda","Diani","Msambweni","Lunga Lunga","Kinango","Tiwi","Matuga"],
  "Laikipia": ["Nanyuki","Nyahururu","Rumuruti","Doldol","Kinamba"],
  "Lamu": ["Lamu Town","Mokowe","Faza","Mpeketoni","Witu"],
  "Machakos": ["Machakos Town","Mavoko","Athi River","Kangundo","Matuu","Mwala","Tala","Kithimani"],
  "Makueni": ["Wote","Makindu","Mtito Andei","Kibwezi","Mukaa","Kathonzweni","Emali"],
  "Mandera": ["Mandera Town","El Wak","Rhamu","Takaba","Banisa","Lafey"],
  "Marsabit": ["Marsabit Town","Moyale Town","Laisamis","North Horr","Loiyangalani","Sololo"],
  "Meru": ["Meru Town","Maua","Nkubu","Timau","Mikinduri","Mitunguu","Gakoromone","Kangeta"],
  "Migori": ["Migori Town","Rongo Town","Kehancha","Awendo","Isebania","Macalder","Suna","Uriri"],
  "Mombasa": ["Mvita","Nyali","Kisauni","Likoni","Changamwe","Jomvu","Mwembe Tayari","Kongowea","Mackinnon","Tudor"],
  "Murang'a": ["Murang'a Town","Kangema","Kandara","Gatanga","Maragua","Kenol","Kiriaini"],
  "Nairobi City": ["Westlands","CBD","Karen","Eastlands","Roysambu","Embakasi","Langata","Kawangware Market","Gikomba Market","Kibera Market","Mathare Market","Umoja Market","Kayole Market","Dandora Market","Kariobangi Market","Dagoretti Market","Parklands Market","Gigiri Market","Lavington Market","South B Market","South C Market","Buruburu Market","Donholm Market","Zimmerman Market","Kasarani Market","Ruaka Bypass Market"],
  "Nakuru": ["Nakuru Town","Naivasha Town","Gilgil Town","Molo Town","Njoro Market","Subukia Market","Rongai Market","Mai Mahiu Market","Elburgon Market","Bahati Market"],
  "Nandi": ["Kapsabet","Nandi Hills Market","Mosoriot Market","Kabiyet Market","Kaiboi Market","Kobujoi Market"],
  "Narok": ["Narok Town","Kilgoris Market","Ololulunga Market","Suswa Market","Lemek Market"],
  "Nyamira": ["Nyamira Town","Nyansiongo Market","Keroka Market","Esise Market","Ekerenyo Market","Manga Market"],
  "Nyandarua": ["Ol Kalou","Nyahururu","Engineer Market","Ol Joro Orok Market","Njabini Market"],
  "Nyeri": ["Nyeri Town","Othaya Market","Mukurweini Market","Karatina Market","Endarasha Market","Narumoru Market","Chaka Market"],
  "Samburu": ["Maralal","Baragoi Market","Wamba Market","Archers Post Market"],
  "Siaya": ["Siaya Town","Bondo Town","Ugunja Market","Usenge Market","Ngiya Market","Yala Market","Akala Market","Ukwala Market"],
  "Taita Taveta": ["Voi","Taveta","Wundanyi Market","Mwatate Market","Maungu Market"],
  "Tana River": ["Hola","Garsen","Bura Market","Madogo Market","Kipini Market"],
  "Tharaka-Nithi": ["Chuka","Chogoria","Marimanti Market","Kathwana Market"],
  "Trans-Nzoia": ["Kitale Town","Endebess Market","Kachibora Market","Kiminini Market","Kwanza Market","Cherangany Market"],
  "Turkana": ["Lodwar","Kakuma Market","Lokichar Market","Lokitaung Market","Lokichoggio Market"],
  "Uasin Gishu": ["Eldoret Town","Turbo Town","Moiben Market","Soy Market","Ziwa Market","Burnt Forest Market","Kesses Market"],
  "Vihiga": ["Vihiga Town","Luanda Market","Mbale Town","Emuhaya Market","Sabatia Market","Chavakali Market","Majengo Market","Kaimosi Market"],
  "Wajir": ["Wajir Town","Habaswein Market","Tarbaj Market","Wajir South Market","Eldas Market"],
  "West Pokot": ["Kapenguria","Makutano Market","Sigor Market","Chepareria Market","Kacheliba Market"]
}
