export const countyTowns: Record<string, string[]> = {
  "Baringo": ["Kabarnet","Eldama Ravine","Marigat","Mogotio"],
  "Bomet": ["Bomet Town","Sotik","Longisa"],
  "Bungoma": ["Bungoma Town","Kimilili","Webuye","Sirisia","Chwele","Bumula","Malakisi"],
  "Busia": ["Busia Town","Malaba","Nambale","Bumala","Port Victoria","Funyula"],
  "Elgeyo-Marakwet": ["Iten","Kapsowar"],
  "Embu": ["Embu Town","Runyenjes","Kiritiri","Siakago"],
  "Garissa": ["Garissa Town","Dadaab","Ijara"],
  "Homa Bay": ["Homa Bay Town","Oyugis","Mbita","Ndhiwa","Rodi Kopany"],
  "Isiolo": ["Isiolo Town","Merti","Garbatulla"],
  "Kajiado": ["Kajiado Town","Ngong","Kitengela","Kiserian","Ongata Rongai","Namanga"],
  "Kakamega": ["Kakamega Town","Mumias Town","Mumias Market","Shianda Market","Ekero Market","Shibale Market","Butere Town","Butere Market","Malava Town","Malava Market","Matungu Market","Khwisero Market","Lurambi","Lugari","Likuyani","Navakholo","Shinyalu","Bukura","Lumakanda"],
  "Kericho": ["Kericho Town","Litein","Londiani"],
  "Kiambu": ["Kiambu Town","Thika Town","Ruiru","Limuru","Kikuyu","Juja","Gatundu"],
  "Kilifi": ["Kilifi Town","Malindi","Watamu","Mariakani","Mtwapa"],
  "Kirinyaga": ["Kerugoya","Kagio","Sagana","Kutus"],
  "Kisii": ["Kisii Town","Ogembo","Suneka","Keroka"],
  "Kisumu": ["Kisumu Town","Maseno","Ahero","Kombewa","Kondele"],
  "Kitui": ["Kitui Town","Mwingi","Mutomo"],
  "Kwale": ["Kwale Town","Ukunda","Diani","Msambweni"],
  "Laikipia": ["Nanyuki","Nyahururu","Rumuruti"],
  "Lamu": ["Lamu Town","Mokowe","Mpeketoni"],
  "Machakos": ["Machakos Town","Mavoko","Athi River","Kangundo","Matuu","Tala"],
  "Makueni": ["Wote","Makindu","Mtito Andei","Kibwezi","Emali"],
  "Mandera": ["Mandera Town","El Wak","Rhamu"],
  "Marsabit": ["Marsabit Town","Moyale","Laisamis"],
  "Meru": ["Meru Town","Maua","Nkubu","Timau"],
  "Migori": ["Migori Town","Rongo","Kehancha","Awendo","Isebania"],
  "Mombasa": ["Mvita","Nyali","Kisauni","Likoni","Changamwe","Kongowea"],
  "Murang'a": ["Murang'a Town","Kangema","Maragua","Kenol"],
  "Nairobi City": ["Westlands","CBD","Karen","Eastlands","Roysambu","Embakasi","Langata","Kawangware","Gikomba","Kibera","Mathare","Umoja","Kayole","Dandora","Kariobangi","Dagoretti","Parklands","Buruburu","Donholm","Kasarani","Ruaka","South B","South C","Lavington"],
  "Nakuru": ["Nakuru Town","Naivasha","Gilgil","Molo","Njoro","Rongai","Bahati"],
  "Nandi": ["Kapsabet","Nandi Hills","Mosoriot"],
  "Narok": ["Narok Town","Kilgoris","Suswa"],
  "Nyamira": ["Nyamira Town","Nyansiongo","Keroka","Manga"],
  "Nyandarua": ["Ol Kalou","Nyahururu","Engineer"],
  "Nyeri": ["Nyeri Town","Othaya","Karatina","Narumoru"],
  "Samburu": ["Maralal","Baragoi","Wamba"],
  "Siaya": ["Siaya Town","Bondo","Ugunja","Usenge","Yala"],
  "Taita Taveta": ["Voi","Taveta","Wundanyi"],
  "Tana River": ["Hola","Garsen","Bura"],
  "Tharaka-Nithi": ["Chuka","Chogoria","Marimanti"],
  "Trans-Nzoia": ["Kitale","Endebess","Kiminini"],
  "Turkana": ["Lodwar","Kakuma","Lokichar"],
  "Uasin Gishu": ["Eldoret","Turbo","Moiben","Burnt Forest"],
  "Vihiga": ["Vihiga Town","Luanda","Mbale","Sabatia","Chavakali"],
  "Wajir": ["Wajir Town","Habaswein","Tarbaj"],
  "West Pokot": ["Kapenguria","Makutano","Sigor"]
}
